### ISSUE TITLE
what is the purpose of that fork ?

### ISSUE THREAD

**Issue by raphaelauv** [pulumi/terraform-provider-google-beta#2]
Hello, what is the purpose of that fork ?

( https://github.com/hashicorp/terraform-provider-google-beta )

**Comment by stack72** [comment]
Hi @raphaelauv 

The purpose of the fork is so that we can make changes to the TF based provider that the pulumi provider is based upon. These are changes such as fixing a small bug before it makes it's way through to the upstream provider

Paul

**Comment by raphaelauv** [comment]
alright , thanks
